version: '3'

services:
  nginx:
    build: .
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./var/log/nginx/debug.log:/var/log/nginx/debug.log
    ports:
      - "8080:80"